workflows:
  android-app:
    name: chess_front
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
      flutter: stable
      java: 17
    scripts:
      - name: Set up Java and Flutter
        script: |
          java -version
          flutter doctor -v
          
      - name: Flutter build preparation
        script: |
          flutter clean
          flutter pub get
          
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi
          
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "android/local.properties"
          
      - name: Update Gradle configuration
        script: |
          cd android
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          chmod +x gradlew
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip" > gradle/wrapper/gradle-wrapper.properties
          ./gradlew --version
          cd ..
          
      - name: Fix Stockfish AndroidManifest
        script: |
          STOCKFISH_MANIFEST="/Users/builder/.pub-cache/hosted/pub.dev/stockfish-1.5.0/android/src/main/AndroidManifest.xml"
          if [ -f "$STOCKFISH_MANIFEST" ]; then
            cp "$STOCKFISH_MANIFEST" "${STOCKFISH_MANIFEST}.backup"
            sed -i '' 's/package="com.stockfish"//g' "$STOCKFISH_MANIFEST"
          fi

      - name: Update Android build configuration
        script: |
          GRADLE_FILE="android/app/build.gradle"
          if [ -f "$GRADLE_FILE" ]; then
            cp "$GRADLE_FILE" "${GRADLE_FILE}.backup"
            sed -i '' 's/compileSdkVersion.*/compileSdkVersion 33/g' "$GRADLE_FILE"
            sed -i '' 's/targetSdkVersion.*/targetSdkVersion 33/g' "$GRADLE_FILE"
            echo "namespace 'com.example.chess_front'" >> "$GRADLE_FILE"
          fi
          
          # Mettre à jour aussi le build.gradle de Stockfish
          STOCKFISH_GRADLE="/Users/builder/.pub-cache/hosted/pub.dev/stockfish-1.5.0/android/build.gradle"
          if [ -f "$STOCKFISH_GRADLE" ]; then
            cp "$STOCKFISH_GRADLE" "${STOCKFISH_GRADLE}.backup"
            sed -i '' 's/compileSdkVersion.*/compileSdkVersion 33/g' "$STOCKFISH_GRADLE"
            sed -i '' 's/targetSdkVersion.*/targetSdkVersion 33/g' "$STOCKFISH_GRADLE"
          fi
          
      - name: Build Android release
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/mapping/release/mapping.txt
      
    publishing:
      email:
        recipients:
          - diopsamba408@gmail.com
        notify:
          success: true
          failure: true