workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
      flutter: stable
    scripts:
      - name: Flutter build preparation
        script: |
          # Installer les dépendances Flutter
          flutter pub get
          
          # Vérifier que le dossier android existe
          if [ ! -d "android" ]; then
            echo "Dossier android non trouvé!"
            exit 1
          fi
          
          # Afficher la structure du projet
          echo "Structure du projet:"
          ls -la
          echo "Contenu du dossier android:"
          ls -la android/
          
      - name: Set up local properties
        script: |
          cd android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
          cd ..
          
      - name: Verify Gradle files
        script: |
          cd android
          
          # Vérifier si gradlew existe
          if [ ! -f "gradlew" ]; then
            echo "gradlew non trouvé, tentative de génération..."
            flutter create --platforms=android .
            
            # Vérifier à nouveau
            if [ ! -f "gradlew" ]; then
              echo "Échec de la création de gradlew"
              exit 1
            fi
          fi
          
          # Rendre gradlew exécutable
          chmod +x gradlew
          
          # Afficher la version de Gradle
          ./gradlew --version
          cd ..
          
      - name: Build Android release
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
      - android/app/build/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - diopsamba408@gmail.com