workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
      flutter: stable
      java: 17.0.0
    scripts:
      - name: Environment Setup
        script: |
          # Afficher les versions
          java -version
          flutter --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          
      - name: Flutter Dependencies
        script: |
          # Installation des dépendances
          flutter pub get
          
          # Vérification de Flutter
          flutter doctor -v
          
      - name: Android Setup
        script: |
          # Vérifier si on est dans le bon dossier
          pwd
          ls -la
          
          # Aller dans le dossier android
          cd android
          
          # Créer local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
          
          # Vérifier les fichiers Gradle
          ls -la
          
          # Si gradlew n'existe pas, le générer
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          
          # Rendre gradlew exécutable
          chmod +x gradlew
          
          # Vérifier la version de Gradle
          ./gradlew --version
          
      - name: Update build.gradle
        script: |
          cd android
          
          # Mettre à jour le build.gradle si nécessaire
          if [ -f "build.gradle" ]; then
            echo "Updating build.gradle..."
            sed -i '' 's/compileSdkVersion .*/compileSdkVersion 33/g' app/build.gradle
            sed -i '' 's/targetSdkVersion .*/targetSdkVersion 33/g' app/build.gradle
            sed -i '' 's/minSdkVersion .*/minSdkVersion 21/g' app/build.gradle
          fi
          
      - name: Build Android Release
        script: |
          cd android
          # Clean build
          ./gradlew clean
          
          # Build avec logs détaillés
          ./gradlew assembleRelease --debug
          
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
      - android/app/build/outputs/mapping/release/mapping.txt
      
    publishing:
      email:
        recipients:
          - diopsamba408@gmail.com
        notify:
          success: true
          failure: true