workflows:
  android-app:
    name: chess_front
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
      flutter: stable
      java: 17
    scripts:
      - name: Set up Java and Flutter
        script: |
          java -version
          flutter doctor -v
          
      - name: Flutter build preparation
        script: |
          flutter clean
          flutter pub get
          
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi
          
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "android/local.properties"
          
      - name: Update Gradle configuration
        script: |
          cd android
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          chmod +x gradlew
          
          # Ajout de la mise à jour de la version Gradle
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip" > gradle/wrapper/gradle-wrapper.properties
          
          ./gradlew --version
          cd ..
          
      - name: Build Android release
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/mapping/release/mapping.txt
      
    publishing:
      email:
        recipients:
          - diopsamba408@gmail.com
        notify:
          success: true
          failure: true