workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
    scripts:
      - name: Set up project
        script: |
          # Vérifier si nous sommes dans le bon répertoire
          echo "Current directory:"
          pwd
          ls -la
          
          # S'assurer d'être dans le dossier android
          cd android
          
          # Vérifier le contenu du dossier android
          echo "Android directory content:"
          ls -la
          
      - name: Set up local properties
        script: |
          cd android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "local.properties"
          
      - name: Build Android release
        script: |
          cd android
          # Utiliser le gradlew existant
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
      - android/app/build/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - diopsamba408@gmail.com