workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Check directory structure
        script: |
          pwd
          ls -la
      - name: Install Gradle Wrapper
        script: |
          gradle wrapper
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Build Android release
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/**/*.apk
      - app/build/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - diopsamba408@gmail.com